---
- name: Create MySQL database and user
  hosts: localhost
  vars_files:
    - mysql_credentials.yml
  tasks:
    - name: Create database
      community.mysql.mysql_db:
        name: database_test
        state: present

    - name: Create user
      community.mysql.mysql_user:
        name: "{{ mysql_username }}"
        password: "{{ mysql_password }}"
        host: localhost
        priv: '*.*:ALL,GRANT'
        state: present

